title: Site
pages: false
files: false

fields:
    title:
        label: Titre
        type: text

    home_line:
        label: Page d'accueil
        type: line

    home_welcome:
        label: Bouton page d'accueil
        type: text

    nav_line:
        label: Navigation
        type: line

    blog_line:
        label: Blog
        type: line

    blog_readmore:
        label: Lire la suite
        type: text
        required: true

    blog_goBack:
        label: Retour au blog
        type: text
        required: true
